### ISSUE TITLE
Add skipFailures flag option to log violations but not fail test

### ISSUE THREAD

**Issue by Valiantsin2021** [sclavijosuero/wick-a11y#15]
Native cypress-axe has the option skipFailure that disables assertions based on violations and only logs violations to the console output. This enabled you to see violations while allowing your tests to pass. This should be used as a temporary measure while you address accessibility violations.
It would be nice to have this option in cy.checkAccessibility method params

**Comment by sclavijosuero** [comment]
Resolved in release https://github.com/sclavijosuero/wick-a11y/releases/tag/v1.4.0 with new option parameter `onlyWarnImpacts`.
