### ISSUE TITLE
Getting error while running accessibility test

### ISSUE THREAD

**Issue by SubramanyamPalla** [sclavijosuero/wick-a11y#2]
Hi @sclavijosuero ,

Thank you so much for the plugin, I started using it in my current project and experienced the below error while running the script.

**NOTE:** We are using the retry mechanism in our project, if the first attempt is filed, we will try for the 2nd attempt.

**First Attempt**: Got the correct outcome

![image](https://github.com/user-attachments/assets/7606d794-88c4-463d-80ce-62d30b1a0537)

**Second Attempt**: The first attempt is expected but the cypress considering that is a failure and trying for 2nd attempt

![image](https://github.com/user-attachments/assets/8868c797-cf83-4f63-a5d2-c6b76efc3882)

**Comment by sclavijosuero** [comment]
This issue has been addressed in the release v1.1.1.
Closing the issue.
